In [1]:
import pandas as pd
from PIL import Image
from IPython.display import display
import os
import numpy as np

In [2]:
df = pd.read_csv('../raw_data/RFMiD_Training_Labels.csv')
df.head()

,ID,Disease_Risk,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df_unhealthy = df[df.Disease_Risk == 1]
df_unhealthy

,ID,Disease_Risk,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,1910,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1913,1914,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1914,1915,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1915,1916,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1916,1917,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df_unhealthy_noID = df_unhealthy.set_index('ID')
df_unhealthy_noRisk = df_unhealthy.drop(['Disease_Risk'], axis=1)
df_unhealthy_noIDRisk = df_unhealthy_noID.drop(['Disease_Risk'], axis=1)
df_unhealthy_noIDRisk
# df_unhealthy_noID
# df_unhealthy.loc[[1]]
# df_unhealthy.loc[1].sum(axis=0)

,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,LS,MS,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
ID,,,,,,,,,,,,,,,,,,,,,
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1910,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1914,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1915,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1916,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1917,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
rows = []
for row in df_unhealthy.ID:
    rows.append(row)
len(rows)
# rows

1519

In [6]:
no_overlapping_rows = []
for row in rows:
    if df_unhealthy_noIDRisk.loc[row].sum(axis=0) == 1:
        no_overlapping_rows.append(row)

len(no_overlapping_rows)
# no_overlapping_rows

1061

In [7]:
ID_list = df_unhealthy_noRisk['ID'].tolist()
len(ID_list)
ID_list

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 11,
 12,
 13,
 14,
 15,
 18,
 19,
 20,
 22,
 23,
 24,
 25,
 26,
 27,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 82,
 84,
 85,
 86,
 87,
 88,
 89,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 149,
 150,
 151,
 152,
 155,
 156,
 157,
 158,
 161,
 162,
 163,
 164,
 165,
 166,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 176,
 177,
 178,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 207,
 208,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 249,
 250,
 251,
 252,
 253,
 254,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 267,
 268,
 269,
 272,
 273,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 315,
 316,
 317,
 318,
 319,
 321,
 322,
 323,
 324,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 337,
 338,
 340,
 341,
 342,
 343,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 376,
 377,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 407,
 408,
 409,
 411,
 412,
 413,
 415,
 416,
 417,
 418,
 419,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 432,
 433,
 434,
 436,
 437,
 438,
 439,
 440,
 441,
 444,
 445,
 446,
 447,
 448,
 450,
 451,
 453,
 455,
 456,
 457,
 459,
 460,
 461,
 463,
 464,
 465,
 467,
 468,
 469,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 483,
 484,
 485,
 486,
 487,
 488,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 532,
 533,
 534,
 535,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 580,
 581,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 595,
 596,
 597,
 599,
 600,
 602,
 603,
 604,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 643,
 644,
 645,
 646,
 647,
 648,
 650,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 681,
 682,
 683,
 685,
 686,
 687,
 688,
 689,
 691,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 702,
 703,
 704,
 705,
 706,
 707,
 709,
 710,
 711,
 712,
 713,
 714,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 729,
 731,
 732,
 733,
 734,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 796,
 799,
 800,
 804,
 806,
 807,
 808,
 809,
 810,
 811,
 814,
 816,
 817,
 818,
 819,
 820,
 821,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 835,
 836,
 837,
 838,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 851,
 853,
 854,
 855,
 856,
 857,
 858,
 860,
 861,
 862,
 864,
 865,
 866,
 867,
 869,
 870,
 871,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 884,
 886,
 887,
 888,
 890,
 891,
 892,
 894,
 897,
 902,
 903,
 906,
 907,
 909,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 929,
 930,
 932,
 933,
 934,
 935,
 937,
 938,
 939,
 941,
 943,
 945,
 946,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 966,
 967,
 968,
 970,
 971,
 972,
 973,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 998,
 1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1009,
 1011,
 1012,
 1013,
 1016,
 1017,
 1019,
 1020,
 1021,
 1022,
 1023,
 1025,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1033,
 1034,
 1036,
 1037,
 1038,
 1039,
 1040,
 1042,
 1043,
 1044,
 1047,
 1048,
 1049,
 1050,
 1051,
 1053,
 1054,
 1055,
 1056,
 1057,
 1058,
 1059,
 1060,
 1061,
 1062,
 1065,
 1066,
 1067,
 1068,
 1069,
 1070,
 1073,
 1074,
 1075,
 1076,
 1078,
 1079,
 1080,
 1081,
 1083,
 1084,
 1087,
 1088,
 1089,
 1090,
 1091,
 1092,
 1093,
 1094,
 1095,
 1096,
 1097,
 1098,
 1099,
 1100,
 1103,
 1104,
 1105,
 1106,
 1107,
 1108,
 1110,
 1111,
 1114,
 1115,
 1116,
 1117,
 1118,
 1119,
 1120,
 1121,
 1122,
 1123,
 1125,
 1126,
 1127,
 1128,
 1129,
 1130,
 1131,
 1132,
 1133,
 1136,
 1138,
 1139,
 1140,
 1141,
 1142,
 1143,
 1144,
 1146,
 1148,
 1149,
 1150,
 1151,
 1152,
 1154,
 1155,
 1156,
 1157,
 1158,
 1159,
 1160,
 1161,
 1162,
 1163,
 1164,
 1165,
 1166,
 1167,
 1168,
 1169,
 1170,
 1171,
 1172,
 1173,
 1174,
 1175,
 1177,
 1178,
 1179,
 1180,
 1181,
 1182,
 1183,
 1184,
 1186,
 1187,
 1190,
 1191,
 1192,
 1195,
 1196,
 1197,
 ...]

In [8]:
overlapping_list = []
for row in ID_list:
    if row not in no_overlapping_rows:
        overlapping_list.append(row)

len(overlapping_list)

458

In [9]:
for number in overlapping_list:
    df_unhealthy = df_unhealthy[df_unhealthy.ID != number]

df_unhealthy

,ID,Disease_Risk,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,9,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
12,13,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1908,1909,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1909,1910,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1913,1914,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1914,1915,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1915,1916,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df_unhealthy_noID = df_unhealthy.set_index('ID')
df_unhealthy_noRisk = df_unhealthy.drop(['Disease_Risk'], axis=1)
df_unhealthy_noIDRisk = df_unhealthy_noID.drop(['Disease_Risk'], axis=1)

In [11]:
# df_DR = df.loc[:, df.columns.intersection(['DR'])]
# df_DR = df_DR[df_DR.DR == 1]
# df_DR.shape
# df_DR.head()

In [12]:
# df_DR = df_unhealthy.loc[:, df_unhealthy.columns.intersection(['DR'])]
# df_DR = df_DR[df_DR.DR == 1]
# df_DR.shape

In [13]:
# df_ARMD = df.loc[:, df.columns.intersection(['ARMD'])]
# df_ARMD = df_ARMD[df_ARMD.ARMD == 1]
# df_ARMD.shape

In [14]:
# df_ARMD = df_unhealthy.loc[:, df_unhealthy.columns.intersection(['ARMD'])]
# df_ARMD = df_ARMD[df_ARMD.ARMD == 1]
# df_ARMD.shape[0]

In [15]:
# df_MH = df.loc[:, df.columns.intersection(['MH'])]
# df_MH = df_MH[df_MH.MH == 1]
# df_MH.shape

In [16]:
# df_unhealthy[['DR']]

In [17]:
disease_list = df_unhealthy_noIDRisk.columns.values.tolist()
# len(disease_list)

no_overlap_disease_dict = {}
for cols in disease_list:
    df_disease = df_unhealthy_noIDRisk[[cols]]
    df_disease = df_disease[df_disease[cols] == 1]
    no_overlap_disease_dict[cols] = df_disease.shape[0]

no_overlap_disease_dict

{'DR': 240,
 'ARMD': 34,
 'MH': 180,
 'DN': 89,
 'MYA': 46,
 'BRVO': 54,
 'TSLN': 23,
 'ERM': 8,
 'LS': 2,
 'MS': 4,
 'CSR': 32,
 'ODC': 119,
 'CRVO': 26,
 'TV': 0,
 'AH': 8,
 'ODP': 17,
 'ODE': 52,
 'ST': 3,
 'AION': 13,
 'PT': 8,
 'RT': 5,
 'RS': 39,
 'CRS': 20,
 'EDN': 4,
 'RPEC': 15,
 'MHL': 5,
 'RP': 4,
 'CWS': 1,
 'CB': 0,
 'ODPM': 0,
 'PRH': 1,
 'MNF': 1,
 'HR': 0,
 'CRAO': 1,
 'TD': 0,
 'CME': 1,
 'PTCR': 3,
 'CF': 0,
 'VH': 0,
 'MCA': 0,
 'VS': 0,
 'BRAO': 1,
 'PLQ': 1,
 'HPED': 1,
 'CL': 0}

In [18]:
sorted_dict = {k: v for k, v in sorted(no_overlap_disease_dict.items(), key=lambda item: item[1], reverse=True)}
# for value in sorted_dict.values():
#     if value == 0:
#         del sorted_dict[]

sorted_dict = {key:val for key, val in sorted_dict.items() if val != 0}

print(len(sorted_dict))
print(sorted_dict)

35
{'DR': 240, 'MH': 180, 'ODC': 119, 'DN': 89, 'BRVO': 54, 'ODE': 52, 'MYA': 46, 'RS': 39, 'ARMD': 34, 'CSR': 32, 'CRVO': 26, 'TSLN': 23, 'CRS': 20, 'ODP': 17, 'RPEC': 15, 'AION': 13, 'ERM': 8, 'AH': 8, 'PT': 8, 'RT': 5, 'MHL': 5, 'MS': 4, 'EDN': 4, 'RP': 4, 'ST': 3, 'PTCR': 3, 'LS': 2, 'CWS': 1, 'PRH': 1, 'MNF': 1, 'CRAO': 1, 'CME': 1, 'BRAO': 1, 'PLQ': 1, 'HPED': 1}

In [19]:
# keep_diseases = []
# for disease in no_overlap_disease_dict.keys():
#     if no_overlap_disease_dict[disease] > 80:
#         keep_diseases.append(disease)
# keep_diseases

for disease in no_overlap_disease_dict.keys():
    if no_overlap_disease_dict[disease] > 80:
        print(f"{disease} - {no_overlap_disease_dict[disease]}")

DR - 240
MH - 180
DN - 89
ODC - 119

In [20]:
df_others_indexID = df_unhealthy_noIDRisk.drop(['DR','MH','ODC','DN'], axis=1)
df_others_indexID['Others'] = df_others_indexID.sum(axis=1)
df_others_indexID

df_others_indexID = df_others_indexID[['Others']]
df_others_indexID
df_others_indexID.value_counts()

Others
0         628
1         433
Name: count, dtype: int64

In [21]:
df_unhealthy_top4 = df_unhealthy_noIDRisk[['DR','MH','ODC','DN']]
df_unhealthy_top4

      DR  MH  ODC  DN
ID
1      1   0    0   0
2      1   0    0   0
3      1   0    0   0
9      0   0    0   0
13     0   0    0   1
...   ..  ..  ...  ..
1909   0   0    0   0
1910   0   0    0   0
1914   0   0    0   0
1915   0   0    0   0
1916   0   0    0   0

[1061 rows x 4 columns]

In [22]:
df_unhealthy_top4_others = pd.concat([df_unhealthy_top4, df_others_indexID], axis=1)
df_unhealthy_top4_others
# df_unhealthy_top4_others.index
df_unhealthy_top4_others.value_counts()

DR  MH  ODC  DN  Others
0   0   0    0   1         433
1   0   0    0   0         240
0   1   0    0   0         180
    0   1    0   0         119
        0    1   0          89
Name: count, dtype: int64

In [23]:
# HERE

In [24]:
import pandas as pd
from PIL import Image
from IPython.display import display
import os
import numpy as np

In [25]:
# TEST

cut_off = 80
df = pd.read_csv('../raw_data/RFMiD_Training_Labels.csv')
df_unhealthy = df[df.Disease_Risk == 1]
df_unhealthy_noID = df_unhealthy.set_index('ID')
df_unhealthy_noRisk = df_unhealthy.drop(['Disease_Risk'], axis=1)
df_unhealthy_noIDRisk = df_unhealthy_noID.drop(['Disease_Risk'], axis=1)

rows = []
for row in df_unhealthy.ID:
    rows.append(row)

no_overlapping_rows = []
for row in rows:
    if df_unhealthy_noIDRisk.loc[row].sum(axis=0) == 1:
        no_overlapping_rows.append(row)

ID_list = df_unhealthy_noRisk['ID'].tolist()

overlapping_list = []
for row in ID_list:
    if row not in no_overlapping_rows:
        overlapping_list.append(row)

for number in overlapping_list:
    df_unhealthy = df_unhealthy[df_unhealthy.ID != number]

df_unhealthy_noID = df_unhealthy.set_index('ID')
# df_unhealthy_noRisk = df_unhealthy.drop(['Disease_Risk'], axis=1)
df_unhealthy_noIDRisk = df_unhealthy_noID.drop(['Disease_Risk'], axis=1)

disease_list = df_unhealthy_noIDRisk.columns.values.tolist()

no_overlap_disease_dict = {}
for cols in disease_list:
    df_disease = df_unhealthy_noIDRisk[[cols]]
    df_disease = df_disease[df_disease[cols] == 1]
    no_overlap_disease_dict[cols] = df_disease.shape[0]

# sorted_dict = {k: v for k, v in sorted(no_overlap_disease_dict.items(), key=lambda item: item[1], reverse=True)}
# sorted_dict = {key:val for key, val in sorted_dict.items() if val != 0}

keep_diseases = []
for disease in no_overlap_disease_dict.keys():
    if no_overlap_disease_dict[disease] >= cut_off:
        keep_diseases.append(disease)

df_others_indexID = df_unhealthy_noIDRisk.drop(keep_diseases, axis=1)
df_others_indexID['Others'] = df_others_indexID.sum(axis=1)
df_others_indexID = df_others_indexID[['Others']]
df_unhealthy_top= df_unhealthy_noIDRisk[keep_diseases]

df_unhealthy_top_others = pd.concat([df_unhealthy_top, df_others_indexID], axis=1)

df_unhealthy_top_others

      DR  MH  DN  ODC  Others
ID
1      1   0   0    0       0
2      1   0   0    0       0
3      1   0   0    0       0
9      0   0   0    0       1
13     0   0   1    0       0
...   ..  ..  ..  ...     ...
1909   0   0   0    0       1
1910   0   0   0    0       1
1914   0   0   0    0       1
1915   0   0   0    0       1
1916   0   0   0    0       1

[1061 rows x 5 columns]

In [28]:
df_unhealthy_top_others.shape[1]

5

In [27]:
df_category = df.drop(['Disease_Risk'], axis=1)
df_cat_noID = df.drop(['ID','Disease_Risk'], axis=1)
df_cat_indexID = df.drop(['Disease_Risk'], axis=1).set_index('ID')
# df_category
# df_cat_indexID

df_unhealthy_cat = df_unhealthy.drop(['Disease_Risk'], axis=1)
df_unhealthy_cat_noID = df_unhealthy.drop(['ID','Disease_Risk'], axis=1)
df_unhealthy_cat_indexID = df_unhealthy.drop(['Disease_Risk'], axis=1).set_index('ID')

In [20]:
# df_cat_noID.head()
disease_list = df_cat_noID.columns.values.tolist()
# print(disease_list)

In [21]:
disease_count = []
for d_name in disease_list:
    disease_count.append(df[d_name].value_counts())

print(disease_count)

[DR
0    1544
1     376
Name: count, dtype: int64, ARMD
0    1820
1     100
Name: count, dtype: int64, MH
0    1603
1     317
Name: count, dtype: int64, DN
0    1782
1     138
Name: count, dtype: int64, MYA
0    1819
1     101
Name: count, dtype: int64, BRVO
0    1847
1      73
Name: count, dtype: int64, TSLN
0    1734
1     186
Name: count, dtype: int64, ERM
0    1906
1      14
Name: count, dtype: int64, LS
0    1873
1      47
Name: count, dtype: int64, MS
0    1905
1      15
Name: count, dtype: int64, CSR
0    1883
1      37
Name: count, dtype: int64, ODC
0    1638
1     282
Name: count, dtype: int64, CRVO
0    1892
1      28
Name: count, dtype: int64, TV
0    1914
1       6
Name: count, dtype: int64, AH
0    1904
1      16
Name: count, dtype: int64, ODP
0    1855
1      65
Name: count, dtype: int64, ODE
0    1862
1      58
Name: count, dtype: int64, ST
0    1915
1       5
Name: count, dtype: int64, AION
0    1903
1      17
Name: count, dtype: int64, PT
0    1909
1      11
Name: count, dtype: int64, RT
0    1906
1      14
Name: count, dtype: int64, RS
0    1877
1      43
Name: count, dtype: int64, CRS
0    1888
1      32
Name: count, dtype: int64, EDN
0    1905
1      15
Name: count, dtype: int64, RPEC
0    1898
1      22
Name: count, dtype: int64, MHL
0    1909
1      11
Name: count, dtype: int64, RP
0    1914
1       6
Name: count, dtype: int64, CWS
0    1917
1       3
Name: count, dtype: int64, CB
0    1919
1       1
Name: count, dtype: int64, ODPM
0    1920
Name: count, dtype: int64, PRH
0    1918
1       2
Name: count, dtype: int64, MNF
0    1917
1       3
Name: count, dtype: int64, HR
0    1920
Name: count, dtype: int64, CRAO
0    1918
1       2
Name: count, dtype: int64, TD
0    1917
1       3
Name: count, dtype: int64, CME
0    1916
1       4
Name: count, dtype: int64, PTCR
0    1915
1       5
Name: count, dtype: int64, CF
0    1917
1       3
Name: count, dtype: int64, VH
0    1919
1       1
Name: count, dtype: int64, MCA
0    1919
1       1
Name: count, dtype: int64, VS
0    1919
1       1
Name: count, dtype: int64, BRAO
0    1918
1       2
Name: count, dtype: int64, PLQ
0    1919
1       1
Name: count, dtype: int64, HPED
0    1919
1       1
Name: count, dtype: int64, CL
0    1919
1       1
Name: count, dtype: int64]

In [22]:
no_overlap_disease_dict = {}
for cols in disease_list:
    df_disease = df_unhealthy[[cols]]
    df_disease = df_disease[df_disease[cols] == 1]
    no_overlap_disease_dict[cols] = df_disease.shape[0]

no_overlap_disease_dict

# df_disease

{'DR': 240,
 'ARMD': 34,
 'MH': 180,
 'DN': 89,
 'MYA': 46,
 'BRVO': 54,
 'TSLN': 23,
 'ERM': 8,
 'LS': 2,
 'MS': 4,
 'CSR': 32,
 'ODC': 119,
 'CRVO': 26,
 'TV': 0,
 'AH': 8,
 'ODP': 17,
 'ODE': 52,
 'ST': 3,
 'AION': 13,
 'PT': 8,
 'RT': 5,
 'RS': 39,
 'CRS': 20,
 'EDN': 4,
 'RPEC': 15,
 'MHL': 5,
 'RP': 4,
 'CWS': 1,
 'CB': 0,
 'ODPM': 0,
 'PRH': 1,
 'MNF': 1,
 'HR': 0,
 'CRAO': 1,
 'TD': 0,
 'CME': 1,
 'PTCR': 3,
 'CF': 0,
 'VH': 0,
 'MCA': 0,
 'VS': 0,
 'BRAO': 1,
 'PLQ': 1,
 'HPED': 1,
 'CL': 0}

In [23]:
sorted_dict = {k: v for k, v in sorted(no_overlap_disease_dict.items(), key=lambda item: item[1], reverse=True)}
# for value in sorted_dict.values():
#     if value == 0:
#         del sorted_dict[]

sorted_dict = {key:val for key, val in sorted_dict.items() if val != 0}

print(len(sorted_dict))
print(sorted_dict)

35
{'DR': 240, 'MH': 180, 'ODC': 119, 'DN': 89, 'BRVO': 54, 'ODE': 52, 'MYA': 46, 'RS': 39, 'ARMD': 34, 'CSR': 32, 'CRVO': 26, 'TSLN': 23, 'CRS': 20, 'ODP': 17, 'RPEC': 15, 'AION': 13, 'ERM': 8, 'AH': 8, 'PT': 8, 'RT': 5, 'MHL': 5, 'MS': 4, 'EDN': 4, 'RP': 4, 'ST': 3, 'PTCR': 3, 'LS': 2, 'CWS': 1, 'PRH': 1, 'MNF': 1, 'CRAO': 1, 'CME': 1, 'BRAO': 1, 'PLQ': 1, 'HPED': 1}

In [24]:
# keep top 4, keep the rest as "other"
# "others" can still be worked on: if others come up frequenlty, we can remove the anamolies with less instances.

In [30]:
# others = []
# for value in sorted_dict.values():
    # if value < 100:
    #     others = list(sorted_dict.keys())[list(sorted_dict.values()).index(value)]
        # print(list(sorted_dict.keys())[list(sorted_dict.values()).index(value)])
# others

df_cat_others_indexID = df.drop(['Disease_Risk','DR','MH','ODC','DN'], axis=1).set_index('ID')
df_cat_others_indexID['Others'] = df_cat_others_indexID.sum(axis=1)
# df_cat_others_indexID = df_cat_others_indexID[df_cat_others_indexID.Others != 0]
df_cat_others_indexID = df_cat_others_indexID[['Others']]
df_cat_others_indexID
df_cat_others_indexID.value_counts()

df_unhealthy_others_indexID = df_unhealthy_cat.drop(['DR','MH','ODC','DN'], axis=1).set_index('ID')
df_unhealthy_others_indexID['Others'] = df_unhealthy_others_indexID.sum(axis=1)
# df_cat_others_indexID = df_cat_others_indexID[df_cat_others_indexID.Others != 0]
df_unhealthy_others_indexID = df_unhealthy_others_indexID[['Others']]
df_unhealthy_others_indexID
# df_unhealthy_others_indexID.value_counts()

      Others
ID
1          0
2          0
3          0
9          1
13         0
...      ...
1909       1
1910       1
1914       1
1915       1
1916       1

[1061 rows x 1 columns]

In [29]:
df_unhealthy_cat_indexID

,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,LS,MS,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
ID,,,,,,,,,,,,,,,,,,,,,
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1910,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1914,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1915,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1916,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
# SEEMS LIKE THERE ARE STILL OVERLAPPING DISEASES IN THIS DATAFRAME. ^

In [28]:
investigate_overlapping_rows = []
for row in rows:
    if df_unhealthy_cat_indexID.loc[row].sum(axis=0) == 1:
        investigate_overlapping_rows.append(row)
investigate_overlapping_rows

# df_unhealthy_noID.loc[4]

KeyError: 4

In [ ]:
df_test = df_cat_noID.loc[[26]]
df_test = df_cat_noID[df_cat_others_indexID.Others == 1]
df_cat_noID.loc[26].value_counts()
df_cat_noID.loc[26] != 0

/tmp/ipykernel_1738/4186083769.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_test = df_cat_noID[df_cat_others_indexID.Others == 1]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [ ]:
# df_test_dict = {}
# for cols in disease_list:
#     df_testing = df_test[[cols]]
#     df_testing = df_testing[df_testing[cols] == 1]
#     df_test_dict[cols] = df_testing.shape[0]
# df_test_dict

In [ ]:
# df2 = pd.concat([df2, df1["Col3"].rename("Col3_from_df1")], axis=1)

In [ ]:
# df1 = pd.DataFrame({
#     "Col1": [1, 2, 3],
#     "Col2": ["A", "B", "C"],
#     "Col3": ["geeks", "for"]
# })

# # Display the first DataFrame
# print("First DataFrame:")
# display(df1)

# # Create the second DataFrame
# df2 = pd.DataFrame({
#     "C1": [4, 5, 6],
#     "C2": ["D", "E", "F"]
# })

# df2 = pd.concat([df2, df1["Col3"].rename("Col3_from_df1")], axis=1)
# df2