In [1]:
import pandas as pd
from PIL import Image
from IPython.display import display
import os
import numpy as np

In [2]:
df = pd.read_csv('../raw_data/RFMiD_Training_Labels.csv')
df.head()

,ID,Disease_Risk,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df_unhealthy = df[df.Disease_Risk == 1]
df_unhealthy

,ID,Disease_Risk,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,1910,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1913,1914,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1914,1915,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1915,1916,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1916,1917,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [57]:
df_unhealthy_noID = df_unhealthy.set_index('ID')
df_unhealthy_noRisk = df_unhealthy.drop(['Disease_Risk'], axis=1)
df_unhealthy_noIDRisk = df_unhealthy_noID.drop(['Disease_Risk'], axis=1)
df_unhealthy_noIDRisk
# df_unhealthy_noID
# df_unhealthy.loc[[1]]
# df_unhealthy.loc[1].sum(axis=0)

,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,LS,MS,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
ID,,,,,,,,,,,,,,,,,,,,,
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1910,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1914,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1915,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1916,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [55]:
rows = []
for row in df_unhealthy.ID:
    rows.append(row)
len(rows)
# rows

1061

In [62]:
no_overlapping_rows = []
for row in rows:
    if df_unhealthy_noIDRisk.loc[row].sum(axis=0) == 1:
        no_overlapping_rows.append(row)

len(no_overlapping_rows)
# no_overlapping_rows

1061

In [58]:
ID_list = df_unhealthy_noRisk['ID'].tolist()
len(ID_list)
# ID_list

1061

In [61]:
# overlapping_list = []
# for row in ID_list:
#     if row not in no_overlapping_rows:
#         overlapping_list.append(row)

# len(overlapping_list)

In [60]:
# for number in overlapping_list:
#     df_unhealthy = df_unhealthy[df_unhealthy.ID != number]

# df_unhealthy

In [13]:
# df_DR = df.loc[:, df.columns.intersection(['DR'])]
# df_DR = df_DR[df_DR.DR == 1]
# df_DR.shape
# df_DR.head()

In [14]:
# df_DR = df_unhealthy.loc[:, df_unhealthy.columns.intersection(['DR'])]
# df_DR = df_DR[df_DR.DR == 1]
# df_DR.shape

In [15]:
# df_ARMD = df.loc[:, df.columns.intersection(['ARMD'])]
# df_ARMD = df_ARMD[df_ARMD.ARMD == 1]
# df_ARMD.shape

In [16]:
# df_ARMD = df_unhealthy.loc[:, df_unhealthy.columns.intersection(['ARMD'])]
# df_ARMD = df_ARMD[df_ARMD.ARMD == 1]
# df_ARMD.shape[0]

In [17]:
# df_MH = df.loc[:, df.columns.intersection(['MH'])]
# df_MH = df_MH[df_MH.MH == 1]
# df_MH.shape

In [18]:
# df_unhealthy[['DR']]

In [71]:
disease_list = df_unhealthy_noIDRisk.columns.values.tolist()
# len(disease_list)

no_overlap_disease_dict = {}
for cols in disease_list:
    df_disease = df_unhealthy_noIDRisk[[cols]]
    df_disease = df_disease[df_disease[cols] == 1]
    no_overlap_disease_dict[cols] = df_disease.shape[0]

no_overlap_disease_dict

{'DR': 240,
 'ARMD': 34,
 'MH': 180,
 'DN': 89,
 'MYA': 46,
 'BRVO': 54,
 'TSLN': 23,
 'ERM': 8,
 'LS': 2,
 'MS': 4,
 'CSR': 32,
 'ODC': 119,
 'CRVO': 26,
 'TV': 0,
 'AH': 8,
 'ODP': 17,
 'ODE': 52,
 'ST': 3,
 'AION': 13,
 'PT': 8,
 'RT': 5,
 'RS': 39,
 'CRS': 20,
 'EDN': 4,
 'RPEC': 15,
 'MHL': 5,
 'RP': 4,
 'CWS': 1,
 'CB': 0,
 'ODPM': 0,
 'PRH': 1,
 'MNF': 1,
 'HR': 0,
 'CRAO': 1,
 'TD': 0,
 'CME': 1,
 'PTCR': 3,
 'CF': 0,
 'VH': 0,
 'MCA': 0,
 'VS': 0,
 'BRAO': 1,
 'PLQ': 1,
 'HPED': 1,
 'CL': 0}

In [72]:
sorted_dict = {k: v for k, v in sorted(no_overlap_disease_dict.items(), key=lambda item: item[1], reverse=True)}
# for value in sorted_dict.values():
#     if value == 0:
#         del sorted_dict[]

sorted_dict = {key:val for key, val in sorted_dict.items() if val != 0}

print(len(sorted_dict))
print(sorted_dict)

35
{'DR': 240, 'MH': 180, 'ODC': 119, 'DN': 89, 'BRVO': 54, 'ODE': 52, 'MYA': 46, 'RS': 39, 'ARMD': 34, 'CSR': 32, 'CRVO': 26, 'TSLN': 23, 'CRS': 20, 'ODP': 17, 'RPEC': 15, 'AION': 13, 'ERM': 8, 'AH': 8, 'PT': 8, 'RT': 5, 'MHL': 5, 'MS': 4, 'EDN': 4, 'RP': 4, 'ST': 3, 'PTCR': 3, 'LS': 2, 'CWS': 1, 'PRH': 1, 'MNF': 1, 'CRAO': 1, 'CME': 1, 'BRAO': 1, 'PLQ': 1, 'HPED': 1}

In [78]:
df_others_indexID = df_unhealthy_noIDRisk.drop(['DR','MH','ODC','DN'], axis=1)
df_others_indexID['Others'] = df_others_indexID.sum(axis=1)
df_others_indexID

df_others_indexID = df_others_indexID[['Others']]
df_others_indexID
# df_others_indexID.value_counts()

      Others
ID
1          0
2          0
3          0
9          1
13         0
...      ...
1909       1
1910       1
1914       1
1915       1
1916       1

[1061 rows x 1 columns]

In [79]:
df_unhealthy_top4 = df_unhealthy_noIDRisk[['DR','MH','ODC','DN']]
df_unhealthy_top4

      DR  MH  ODC  DN
ID
1      1   0    0   0
2      1   0    0   0
3      1   0    0   0
9      0   0    0   0
13     0   0    0   1
...   ..  ..  ...  ..
1909   0   0    0   0
1910   0   0    0   0
1914   0   0    0   0
1915   0   0    0   0
1916   0   0    0   0

[1061 rows x 4 columns]

In [85]:
df_unhealthy_top4_others = pd.concat([df_unhealthy_top4, df_others_indexID], axis=1)
df_unhealthy_top4_others
df_unhealthy_top4_others.value_counts()

DR  MH  ODC  DN  Others
0   0   0    0   1         433
1   0   0    0   0         240
0   1   0    0   0         180
    0   1    0   0         119
        0    1   0          89
Name: count, dtype: int64

In [ ]:
# HERE

In [19]:
df_category = df.drop(['Disease_Risk'], axis=1)
df_cat_noID = df.drop(['ID','Disease_Risk'], axis=1)
df_cat_indexID = df.drop(['Disease_Risk'], axis=1).set_index('ID')
# df_category
# df_cat_indexID

df_unhealthy_cat = df_unhealthy.drop(['Disease_Risk'], axis=1)
df_unhealthy_cat_noID = df_unhealthy.drop(['ID','Disease_Risk'], axis=1)
df_unhealthy_cat_indexID = df_unhealthy.drop(['Disease_Risk'], axis=1).set_index('ID')

In [20]:
# df_cat_noID.head()
disease_list = df_cat_noID.columns.values.tolist()
# print(disease_list)

In [21]:
disease_count = []
for d_name in disease_list:
    disease_count.append(df[d_name].value_counts())

print(disease_count)

[DR
0    1544
1     376
Name: count, dtype: int64, ARMD
0    1820
1     100
Name: count, dtype: int64, MH
0    1603
1     317
Name: count, dtype: int64, DN
0    1782
1     138
Name: count, dtype: int64, MYA
0    1819
1     101
Name: count, dtype: int64, BRVO
0    1847
1      73
Name: count, dtype: int64, TSLN
0    1734
1     186
Name: count, dtype: int64, ERM
0    1906
1      14
Name: count, dtype: int64, LS
0    1873
1      47
Name: count, dtype: int64, MS
0    1905
1      15
Name: count, dtype: int64, CSR
0    1883
1      37
Name: count, dtype: int64, ODC
0    1638
1     282
Name: count, dtype: int64, CRVO
0    1892
1      28
Name: count, dtype: int64, TV
0    1914
1       6
Name: count, dtype: int64, AH
0    1904
1      16
Name: count, dtype: int64, ODP
0    1855
1      65
Name: count, dtype: int64, ODE
0    1862
1      58
Name: count, dtype: int64, ST
0    1915
1       5
Name: count, dtype: int64, AION
0    1903
1      17
Name: count, dtype: int64, PT
0    1909
1      11
Name: count, dtype: int64, RT
0    1906
1      14
Name: count, dtype: int64, RS
0    1877
1      43
Name: count, dtype: int64, CRS
0    1888
1      32
Name: count, dtype: int64, EDN
0    1905
1      15
Name: count, dtype: int64, RPEC
0    1898
1      22
Name: count, dtype: int64, MHL
0    1909
1      11
Name: count, dtype: int64, RP
0    1914
1       6
Name: count, dtype: int64, CWS
0    1917
1       3
Name: count, dtype: int64, CB
0    1919
1       1
Name: count, dtype: int64, ODPM
0    1920
Name: count, dtype: int64, PRH
0    1918
1       2
Name: count, dtype: int64, MNF
0    1917
1       3
Name: count, dtype: int64, HR
0    1920
Name: count, dtype: int64, CRAO
0    1918
1       2
Name: count, dtype: int64, TD
0    1917
1       3
Name: count, dtype: int64, CME
0    1916
1       4
Name: count, dtype: int64, PTCR
0    1915
1       5
Name: count, dtype: int64, CF
0    1917
1       3
Name: count, dtype: int64, VH
0    1919
1       1
Name: count, dtype: int64, MCA
0    1919
1       1
Name: count, dtype: int64, VS
0    1919
1       1
Name: count, dtype: int64, BRAO
0    1918
1       2
Name: count, dtype: int64, PLQ
0    1919
1       1
Name: count, dtype: int64, HPED
0    1919
1       1
Name: count, dtype: int64, CL
0    1919
1       1
Name: count, dtype: int64]

In [22]:
no_overlap_disease_dict = {}
for cols in disease_list:
    df_disease = df_unhealthy[[cols]]
    df_disease = df_disease[df_disease[cols] == 1]
    no_overlap_disease_dict[cols] = df_disease.shape[0]

no_overlap_disease_dict

# df_disease

{'DR': 240,
 'ARMD': 34,
 'MH': 180,
 'DN': 89,
 'MYA': 46,
 'BRVO': 54,
 'TSLN': 23,
 'ERM': 8,
 'LS': 2,
 'MS': 4,
 'CSR': 32,
 'ODC': 119,
 'CRVO': 26,
 'TV': 0,
 'AH': 8,
 'ODP': 17,
 'ODE': 52,
 'ST': 3,
 'AION': 13,
 'PT': 8,
 'RT': 5,
 'RS': 39,
 'CRS': 20,
 'EDN': 4,
 'RPEC': 15,
 'MHL': 5,
 'RP': 4,
 'CWS': 1,
 'CB': 0,
 'ODPM': 0,
 'PRH': 1,
 'MNF': 1,
 'HR': 0,
 'CRAO': 1,
 'TD': 0,
 'CME': 1,
 'PTCR': 3,
 'CF': 0,
 'VH': 0,
 'MCA': 0,
 'VS': 0,
 'BRAO': 1,
 'PLQ': 1,
 'HPED': 1,
 'CL': 0}

In [23]:
sorted_dict = {k: v for k, v in sorted(no_overlap_disease_dict.items(), key=lambda item: item[1], reverse=True)}
# for value in sorted_dict.values():
#     if value == 0:
#         del sorted_dict[]

sorted_dict = {key:val for key, val in sorted_dict.items() if val != 0}

print(len(sorted_dict))
print(sorted_dict)

35
{'DR': 240, 'MH': 180, 'ODC': 119, 'DN': 89, 'BRVO': 54, 'ODE': 52, 'MYA': 46, 'RS': 39, 'ARMD': 34, 'CSR': 32, 'CRVO': 26, 'TSLN': 23, 'CRS': 20, 'ODP': 17, 'RPEC': 15, 'AION': 13, 'ERM': 8, 'AH': 8, 'PT': 8, 'RT': 5, 'MHL': 5, 'MS': 4, 'EDN': 4, 'RP': 4, 'ST': 3, 'PTCR': 3, 'LS': 2, 'CWS': 1, 'PRH': 1, 'MNF': 1, 'CRAO': 1, 'CME': 1, 'BRAO': 1, 'PLQ': 1, 'HPED': 1}

In [24]:
# keep top 4, keep the rest as "other"
# "others" can still be worked on: if others come up frequenlty, we can remove the anamolies with less instances.

In [30]:
# others = []
# for value in sorted_dict.values():
    # if value < 100:
    #     others = list(sorted_dict.keys())[list(sorted_dict.values()).index(value)]
        # print(list(sorted_dict.keys())[list(sorted_dict.values()).index(value)])
# others

df_cat_others_indexID = df.drop(['Disease_Risk','DR','MH','ODC','DN'], axis=1).set_index('ID')
df_cat_others_indexID['Others'] = df_cat_others_indexID.sum(axis=1)
# df_cat_others_indexID = df_cat_others_indexID[df_cat_others_indexID.Others != 0]
df_cat_others_indexID = df_cat_others_indexID[['Others']]
df_cat_others_indexID
df_cat_others_indexID.value_counts()

df_unhealthy_others_indexID = df_unhealthy_cat.drop(['DR','MH','ODC','DN'], axis=1).set_index('ID')
df_unhealthy_others_indexID['Others'] = df_unhealthy_others_indexID.sum(axis=1)
# df_cat_others_indexID = df_cat_others_indexID[df_cat_others_indexID.Others != 0]
df_unhealthy_others_indexID = df_unhealthy_others_indexID[['Others']]
df_unhealthy_others_indexID
# df_unhealthy_others_indexID.value_counts()

      Others
ID
1          0
2          0
3          0
9          1
13         0
...      ...
1909       1
1910       1
1914       1
1915       1
1916       1

[1061 rows x 1 columns]

In [29]:
df_unhealthy_cat_indexID

,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,LS,MS,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
ID,,,,,,,,,,,,,,,,,,,,,
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1910,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1914,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1915,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1916,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
# SEEMS LIKE THERE ARE STILL OVERLAPPING DISEASES IN THIS DATAFRAME. ^

In [28]:
investigate_overlapping_rows = []
for row in rows:
    if df_unhealthy_cat_indexID.loc[row].sum(axis=0) == 1:
        investigate_overlapping_rows.append(row)
investigate_overlapping_rows

# df_unhealthy_noID.loc[4]

KeyError: 4

In [ ]:
df_test = df_cat_noID.loc[[26]]
df_test = df_cat_noID[df_cat_others_indexID.Others == 1]
df_cat_noID.loc[26].value_counts()
df_cat_noID.loc[26] != 0

/tmp/ipykernel_1738/4186083769.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_test = df_cat_noID[df_cat_others_indexID.Others == 1]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [ ]:
# df_test_dict = {}
# for cols in disease_list:
#     df_testing = df_test[[cols]]
#     df_testing = df_testing[df_testing[cols] == 1]
#     df_test_dict[cols] = df_testing.shape[0]
# df_test_dict

In [ ]:
# df2 = pd.concat([df2, df1["Col3"].rename("Col3_from_df1")], axis=1)

In [ ]:
# df1 = pd.DataFrame({
#     "Col1": [1, 2, 3],
#     "Col2": ["A", "B", "C"],
#     "Col3": ["geeks", "for"]
# })

# # Display the first DataFrame
# print("First DataFrame:")
# display(df1)

# # Create the second DataFrame
# df2 = pd.DataFrame({
#     "C1": [4, 5, 6],
#     "C2": ["D", "E", "F"]
# })

# df2 = pd.concat([df2, df1["Col3"].rename("Col3_from_df1")], axis=1)
# df2