In [4]:
import pandas as pd
from PIL import Image
from IPython.display import display
import os
import numpy as np

In [5]:
df = pd.read_csv('../raw_data/RFMiD_Training_Labels.csv')
df.head()

,ID,Disease_Risk,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df_unhealthy = df[df.Disease_Risk == 1]
df_unhealthy

,ID,Disease_Risk,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,1910,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1913,1914,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1914,1915,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1915,1916,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1916,1917,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
df_unhealthy_noID = df[df.Disease_Risk == 1].set_index('ID')
df_unhealthy_noID

,Disease_Risk,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,LS,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
ID,,,,,,,,,,,,,,,,,,,,,
1,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1910,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1914,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1915,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1916,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1917,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [8]:
# df_unhealthy.loc[[1]]

In [9]:
# df_unhealthy.loc[1].sum(axis=0)

In [10]:
rows = []
for row in df_unhealthy.ID:
    rows.append(row)
# len(rows)

In [11]:
# df_unhealthy_noID.loc[1].sum(axis=0)

In [12]:
no_overlapping_rows = []
for row in rows:
    if df_unhealthy_noID.loc[row].sum(axis=0) < 3:
        no_overlapping_rows.append(row)

# len(no_overlapping_rows)

In [13]:
ID_list = df_unhealthy['ID'].tolist()
# len(ID_list)

In [14]:
overlapping_list = []
for number in ID_list:
    if number not in no_overlapping_rows:
        overlapping_list.append(number)

# len(overlapping_list)

In [15]:
for number in overlapping_list:
    df_unhealthy = df_unhealthy[df_unhealthy.ID != number]

# df_unhealthy

In [16]:
df_DR = df.loc[:, df.columns.intersection(['DR'])]
df_DR = df_DR[df_DR.DR == 1]
# df_DR.shape
# df_DR.head()

In [17]:
df_DR = df_unhealthy.loc[:, df_unhealthy.columns.intersection(['DR'])]
df_DR = df_DR[df_DR.DR == 1]
# df_DR.shape

In [18]:
df_ARMD = df.loc[:, df.columns.intersection(['ARMD'])]
df_ARMD = df_ARMD[df_ARMD.ARMD == 1]
# df_ARMD.shape

In [19]:
df_ARMD = df_unhealthy.loc[:, df_unhealthy.columns.intersection(['ARMD'])]
df_ARMD = df_ARMD[df_ARMD.ARMD == 1]
# df_ARMD.shape[0]

In [20]:
df_MH = df.loc[:, df.columns.intersection(['MH'])]
df_MH = df_MH[df_MH.MH == 1]
# df_MH.shape

In [21]:
# df_unhealthy[['DR']]

In [36]:
df_category = df.drop(['Disease_Risk'], axis=1)
df_cat_noID = df.drop(['ID','Disease_Risk'], axis=1)
df_cat_indexID = df.drop(['Disease_Risk'], axis=1).set_index('ID')
# df_category
# df_cat_indexID

In [23]:
# df_cat_noID.head()
disease_list = df_cat_noID.columns.values.tolist()
# print(disease_list)

In [24]:
disease_count = []
for d_name in disease_list:
    # if
    disease_count.append(df[d_name].value_counts())

# print(disease_count)

In [25]:
no_overlap_disease_dict = {}
for cols in disease_list:
    df_disease = df_unhealthy[[cols]]
    df_disease = df_disease[df_disease[cols] == 1]
    no_overlap_disease_dict[cols] = df_disease.shape[0]

# no_overlap_disease_dict

In [33]:
sorted_dict = {k: v for k, v in sorted(no_overlap_disease_dict.items(), key=lambda item: item[1], reverse=True)}
# for value in sorted_dict.values():
#     if value == 0:
#         del sorted_dict[]

sorted_dict = {key:val for key, val in sorted_dict.items() if val != 0}

print(len(sorted_dict))
print(sorted_dict)

35
{'DR': 240, 'MH': 180, 'ODC': 119, 'DN': 89, 'BRVO': 54, 'ODE': 52, 'MYA': 46, 'RS': 39, 'ARMD': 34, 'CSR': 32, 'CRVO': 26, 'TSLN': 23, 'CRS': 20, 'ODP': 17, 'RPEC': 15, 'AION': 13, 'ERM': 8, 'AH': 8, 'PT': 8, 'RT': 5, 'MHL': 5, 'MS': 4, 'EDN': 4, 'RP': 4, 'ST': 3, 'PTCR': 3, 'LS': 2, 'CWS': 1, 'PRH': 1, 'MNF': 1, 'CRAO': 1, 'CME': 1, 'BRAO': 1, 'PLQ': 1, 'HPED': 1}

In [ ]:
# keep top 4, keep the rest as "other"
# "others" can still be worked on: if others come up frequenlty, we can remove the anamolies with less instances.

In [60]:
# others = []
# for value in sorted_dict.values():
    # if value < 100:
    #     others = list(sorted_dict.keys())[list(sorted_dict.values()).index(value)]
        # print(list(sorted_dict.keys())[list(sorted_dict.values()).index(value)])
# others

df_cat_others_indexID = df.drop(['Disease_Risk','DR','MH','ODC','DN'], axis=1).set_index('ID')
df_cat_others_indexID['Others'] = df_cat_others_indexID.sum(axis=1)
df_cat_others_indexID = df_cat_others_indexID[df_cat_others_indexID.Others != 0]
df_cat_others_indexID = df_cat_others_indexID[['Others']]
df_cat_others_indexID

      Others
ID
5          1
6          2
7          2
8          2
9          1
...      ...
1910       1
1914       1
1915       1
1916       1
1917       1

[812 rows x 1 columns]

In [42]:
# create a sample DataFrame
df_example = pd.DataFrame({'col1': [1, 2, 3], 'col2': [4, 5, 6]})
# df_example
df_example['Fruit Total']= df_example.sum(axis=1)
# merge the two columns into one
# df_example['merged'] = pd.concat([df['col1'], df['col2']])
df_example

   col1  col2  Fruit Total
0     1     4            5
1     2     5            7
2     3     6            9